### ISSUE TITLE
Upgrading to v7

### ISSUE THREAD

**Issue by samullman** [babel/website#2135]
https://babeljs.io/docs/en/v7-migration
https://github.com/babel/babel-upgrade

```
babel --version
6.26.0 (babel-core 6.26.3)
```

**Comment by nicolo-ribaudo** [comment]
Did you see https://babeljs.io/docs/en/v7-migration#scoped-packages?

**Comment by samullman** [comment]
@nicolo-ribaudo I do.

```
lerna ERR! npm run prepare stderr:
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing preset: "/Users/samuelullman/Desktop/blocks/node_modules/@babel/preset-env/lib/index.js")
    at throwVersionError (/Users/samuelullman/Desktop/blocks/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/Users/samuelullman/Desktop/blocks/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at _default (/Users/samuelullman/Desktop/blocks/node_modules/@babel/preset-env/lib/index.js:188:7)
    at /Users/samuelullman/Desktop/blocks/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12

```

**Comment by nicolo-ribaudo** [comment]
You must use `./node_modules/.bin/babel` (which is the `@babel/core` in your package.json), or also upgrade the globally installed one.

**Comment by samullman** [comment]
Ah must globally install scoped package
```
npm install --global @babel/core
```
Before upgrading
```
npm install --global @babel/core
npx babel-upgrade --write --install
```
