### ISSUE TITLE
"NOTE: This plugin is included in @babel/preset-env" is misleading, should state that it's under the shippedProposals flag

### ISSUE THREAD

**Issue by rdsedmundo** [babel/website#2526]
### Problem
The "call-to-action" at the beginning of plugins like [babel-plugin-proposal-class-properties](https://babeljs.io/docs/en/babel-plugin-proposal-class-properties) is really misleading, it says that the plugin is already _included_ in the preset, however, it doesn't say that it's under an option flag, which happens to be presented only at the very end of the documentation.

### Solution
Change to "NOTE: This plugin is included in @babel/preset-env under the [shippedProposals](https://babeljs.io/docs/en/babel-preset-env#shippedproposals) flag".

I'm happy to send a PR if you agree that it makes sense.

**Comment by rdsedmundo** [comment]
I reported this originally because I'm facing an issue with this upgrade in a production system that relates to `webpack.optimization.concatenateModules`. 

I have this code:

```js
class ABC {
	static statuses = [];
}
```

If `concatenateModules` is set to `true` and I use `@babel/preset-env@7.14.0`, `ABC.statuses` is `undefined`, it's getting transpiled to `ABC.ABC_statuses` instead. 

However, if I include `@babel/plugin-proposal-class-properties` manually to the plugins section in the Babel config, it's transpiled properly again.

@JLHwung @nicolo-ribaudo could you think of anything that was changed between when it was a standalone plugin (<7.14.0) and now that it moved to preset-env (>=7.14.0) that could cause this? I know it's vague, I'm trying to come up with a minimal reproduction because it's private code.

**Comment by nicolo-ribaudo** [comment]
Oh this is a really strange bug, since when we don't rename class properties but, even if we did, all the identifiers that Babel generates start with `_` (so it would have been `_statuses` or `_ABC_statuses`).

**Comment by rdsedmundo** [comment]
Thanks for the input. 

I managed to reproduce it: https://github.com/webpack/webpack/issues/13371, it's indeed a webpack problem and not Babel's. 

It was working before with the plugin added manually because the plugin also transpiles `static` properties even if Node runtime already supports it, whereas preset-env is smarter and doesn't. So Babel was transpiling it before webpack had a chance to concatenate the modules, thus the problem didn't appear.

**Comment by heyheyhello** [comment]
@JLHwung I believe the #2528 PR doesn't fully address what @rdsedmundo brought up in the OP. I just landed on this issue because I was about to make a PR+issue about the same problem: 

This is the midleading bit:

![image](https://user-images.githubusercontent.com/44614862/124675507-a7a1c680-de71-11eb-88c4-acd992abe1b2.png)

It implies that because it's _included_ it's safe to remove it from babel-rc if using preset-env, and that's not the case. I jsut ran into "Syntax Error: Missing class properties transform".

Edmundo's suggestion makes the most sense to change to "NOTE: This plugin is included in @babel/preset-env under the shippedProposals flag".

Thank you!

**Comment by JLHwung** [comment]
@heyheyhello 

`@babel/plugin-proposal-class-properties` is enabled behind `shippedProposals` flag in `@babel/preset-env` version [7.12.0, 7.14.0)

`@babel/plugin-proposal-class-properties` is always enabled in `@babel/preset-env` version [7.14.0, +Infinity)

If you come across a missing plugin error, can you post the output of

```
npm ls @babel/preset-env
```

**Comment by heyheyhello** [comment]
Hmm that's odd it's not working for 7.14+. I'm using Storybook with webpack and babel-loader if that makes a difference...

With `package.json` as:

```
  "devDependencies": {
    "@babel/core": "^7.14.6",
    "@babel/plugin-proposal-class-properties": "^7.14.5",
    "@babel/plugin-proposal-private-methods": "^7.14.5",
    "@babel/plugin-proposal-private-property-in-object": "^7.14.5",
    "@babel/plugin-transform-react-jsx": "^7.14.5",
    "@babel/plugin-transform-runtime": "^7.14.5",
    "@babel/plugin-transform-typescript": "^7.14.6",
    "@babel/polyfill": "^7.12.1",
    "@babel/preset-env": "^7.14.7",
    "@storybook/addon-essentials": "^6.3.2",
    "@storybook/addon-links": "^6.3.2",
    "@storybook/addon-storyshots": "^6.3.2",
    "@storybook/addon-storyshots-puppeteer": "^6.3.2",
    "@storybook/react": "^6.3.2",
    "@types/react-router-dom": "^5.1.7",
    "@typescript-eslint/eslint-plugin": "^4.28.2",
    "@typescript-eslint/parser": "^4.28.2",
    "babel-jest": "^27.0.6",
    "babel-loader": "^8.2.2",
    ...
```

And `babel.config.js` as:

```js
module.exports = {
    presets: [
        ['@babel/preset-env', { modules: 'commonjs', targets: { ie: '11' } } ],
    ],
    plugins: [
        // Note to project team: Leave these manually specified! It's to avoid either of:
        // "Error: 'loose' mode configuration must be the same for x, y, z (when they are enabled)."
        // "ModuleBuildError: Module build failed [...] Missing class properties transform."
        // '@babel/plugin-proposal-class-properties',
        // '@babel/plugin-proposal-private-methods',
        // '@babel/plugin-proposal-private-property-in-object',
        '@babel/plugin-transform-runtime',
        '@babel/plugin-transform-react-jsx',
        ['@babel/plugin-transform-typescript', { isTSX: true } ],
    ],
};
```

I see many many errors of the form:

```
ModuleBuildError: Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: ~/my-app/packages/dialogs/src/components/ScheduledExport/index.jsx: Missing class properties transform.
  55 |
  56 | class ScheduledExportDialog extends Component {
> 57 |     static defaultProps = {
     |     ^
  58 |         onCloseModal: () => {},
  59 |     };
  60 |
    at File.buildCodeFrameError (~/my-app/node_modules/@babel/core/lib/transformation/file/file.js:244:12)
    at NodePath.buildCodeFrameError (~/my-app/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/index.js:133:21)
    at pushBody (~/my-app/node_modules/@babel/plugin-transform-classes/lib/transformClass.js:135:20)
    at buildBody (~/my-app/node_modules/@babel/plugin-transform-classes/lib/transformClass.js:109:5)
    at classTransformer (~/my-app/node_modules/@babel/plugin-transform-classes/lib/transformClass.js:545:5)
    at transformClass (~/my-app/node_modules/@babel/plugin-transform-classes/lib/transformClass.js:581:10)
    at PluginPass.ClassExpression (~/my-app/node_modules/@babel/plugin-transform-classes/lib/index.js:67:54)
    at newFn (~/my-app/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:171:21)
    at NodePath._call (~/my-app/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (~/my-app/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (~/my-app/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (~/my-app/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:99:16)
    at TraversalContext.visitSingle (~/my-app/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:73:19)
    at TraversalContext.visit (~/my-app/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:127:19)
    at Function.traverse.node (~/my-app/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (~/my-app/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at ~/my-app/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/NormalModule.js:316:20
    at ~/my-app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at ~/my-app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (~/my-app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at ~/my-app/node_modules/babel-loader/lib/index.js:59:103
```

---

Meanwhile if I uncomment the babel.config.js lines to have

```js
module.exports = {
    presets: [
        ['@babel/preset-env', { modules: 'commonjs', targets: { ie: '11' } } ],
    ],
    plugins: [
        // Note to project team: Leave these manually specified! It's to avoid either of:
        // "Error: 'loose' mode configuration must be the same for x, y, z (when they are enabled)."
        // "ModuleBuildError: Module build failed [...] Missing class properties transform."
        '@babel/plugin-proposal-class-properties',
        '@babel/plugin-proposal-private-methods',
        '@babel/plugin-proposal-private-property-in-object',
        '@babel/plugin-transform-runtime',
        '@babel/plugin-transform-react-jsx',
        ['@babel/plugin-transform-typescript', { isTSX: true } ],
    ],
};
```

It passes with no errors!

---

Also if I try `shippedProposals: true` then _in addition_ to the above errors I also get a hundred of these errors:

```
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-methods.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
        ["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.
```

Which doesn't feel actionable since I want `loose: false` and that's supposed to be the default...

Anyway! No worries it works for me to just have them explicitly listed 😄🎉

```
'@babel/plugin-proposal-class-properties',
'@babel/plugin-proposal-private-methods',
'@babel/plugin-proposal-private-property-in-object',
```

**Comment by JLHwung** [comment]
What's the output of `yarn list @babel/preset-env`?

> ~/my-app/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/index.js:133:21

I can tell from the error trace that in your node_modules there are multiple copies of `@babel/traverse`. Chances are, you may find multiple copies of `@babel/preset-env`, too.

[yarn-deduplicate](https://github.com/atlassian/yarn-deduplicate) always help in this situation.

**Comment by heyheyhello** [comment]
```
❯ yarn list --pattern @babel/preset-env
yarn list v1.22.10
└─ @babel/preset-env@7.14.7
✨  Done in 1.26s.
```

> yarn-deduplicate always helps

Amazing! I only ever use npm and now I'm even more disappointed that my work uses yarn... Thanks for the tip.

```
❯ yarn-deduplicate yarn.lock --list
Package "@babel/code-frame" wants ^7.0.0 and could get 7.14.5, but got 7.12.13
Package "@babel/code-frame" wants ^7.10.4 and could get 7.14.5, but got 7.12.13
Package "@babel/code-frame" wants ^7.12.13 and could get 7.14.5, but got 7.12.13
Package "@babel/code-frame" wants ^7.5.5 and could get 7.14.5, but got 7.12.13
Package "@babel/compat-data" wants ^7.13.11 and could get 7.14.7, but got 7.14.0
Package "@babel/compat-data" wants ^7.13.15 and could get 7.14.7, but got 7.14.0
Package "@babel/core" wants ^7.0.0 and could get 7.14.6, but got 7.14.2
Package "@babel/core" wants ^7.1.0 and could get 7.14.6, but got 7.14.2
Package "@babel/core" wants ^7.7.5 and could get 7.14.6, but got 7.14.2
Package "@babel/generator" wants ^7.12.5 and could get 7.14.5, but got 7.14.2
Package "@babel/generator" wants ^7.14.2 and could get 7.14.5, but got 7.14.2
Package "@babel/helper-annotate-as-pure" wants ^7.0.0 and could get 7.14.5, but got 7.12.13
Package "@babel/helper-annotate-as-pure" wants ^7.12.13 and could get 7.14.5, but got 7.12.13
Package "@babel/helper-compilation-targets" wants ^7.13.0 and could get 7.14.5, but got 7.13.16
Package "@babel/helper-compilation-targets" wants ^7.13.16 and could get 7.14.5, but got 7.13.16
Package "@babel/helper-create-class-features-plugin" wants ^7.13.0 and could get 7.14.6, but got 7.14.2
Package "@babel/helper-create-regexp-features-plugin" wants ^7.12.13 and could get 7.14.5, but got 7.12.17
Package "@babel/helper-function-name" wants ^7.14.2 and could get 7.14.5, but got 7.14.2
Package "@babel/helper-get-function-arity" wants ^7.12.13 and could get 7.14.5, but got 7.12.13
Package "@babel/helper-member-expression-to-functions" wants ^7.13.12 and could get 7.14.7, but got 7.13.12
Package "@babel/helper-module-imports" wants ^7.0.0 and could get 7.14.5, but got 7.13.12
Package "@babel/helper-module-imports" wants ^7.12.13 and could get 7.14.5, but got 7.13.12
Package "@babel/helper-module-imports" wants ^7.13.12 and could get 7.14.5, but got 7.13.12
Package "@babel/helper-module-transforms" wants ^7.12.1 and could get 7.14.5, but got 7.14.2
Package "@babel/helper-module-transforms" wants ^7.14.2 and could get 7.14.5, but got 7.14.2
Package "@babel/helper-optimise-call-expression" wants ^7.12.13 and could get 7.14.5, but got 7.12.13
Package "@babel/helper-plugin-utils" wants ^7.0.0 and could get 7.14.5, but got 7.10.4
Package "@babel/helper-plugin-utils" wants ^7.10.4 and could get 7.14.5, but got 7.10.4
Package "@babel/helper-plugin-utils" wants ^7.8.0 and could get 7.14.5, but got 7.10.4
Package "@babel/helper-plugin-utils" wants ^7.8.3 and could get 7.14.5, but got 7.10.4
Package "@babel/helper-plugin-utils" wants ^7.12.13 and could get 7.14.5, but got 7.13.0
Package "@babel/helper-plugin-utils" wants ^7.13.0 and could get 7.14.5, but got 7.13.0
Package "@babel/helper-replace-supers" wants ^7.13.12 and could get 7.14.5, but got 7.13.12
Package "@babel/helper-simple-access" wants ^7.13.12 and could get 7.14.5, but got 7.13.12
Package "@babel/helper-skip-transparent-expression-wrappers" wants ^7.12.1 and could get 7.14.5, but got 7.12.1
Package "@babel/helper-split-export-declaration" wants ^7.12.13 and could get 7.14.5, but got 7.12.13
Package "@babel/helper-validator-identifier" wants ^7.14.0 and could get 7.14.5, but got 7.14.0
Package "@babel/helper-validator-option" wants ^7.12.17 and could get 7.14.5, but got 7.12.17
Package "@babel/helpers" wants ^7.12.5 and could get 7.14.6, but got 7.14.0
Package "@babel/helpers" wants ^7.14.0 and could get 7.14.6, but got 7.14.0
Package "@babel/highlight" wants ^7.10.4 and could get 7.14.5, but got 7.14.0
Package "@babel/highlight" wants ^7.12.13 and could get 7.14.5, but got 7.14.0
Package "@babel/parser" wants ^7.1.0 and could get 7.14.7, but got 7.14.2
Package "@babel/parser" wants ^7.12.13 and could get 7.14.7, but got 7.14.2
Package "@babel/parser" wants ^7.12.7 and could get 7.14.7, but got 7.14.2
Package "@babel/parser" wants ^7.14.2 and could get 7.14.7, but got 7.14.2
Package "@babel/plugin-proposal-class-properties" wants ^7.12.1 and could get 7.14.5, but got 7.13.0
Package "@babel/plugin-proposal-nullish-coalescing-operator" wants ^7.12.1 and could get 7.14.5, but got 7.14.2
Package "@babel/plugin-proposal-object-rest-spread" wants ^7.12.1 and could get 7.14.7, but got 7.12.1
Package "@babel/plugin-proposal-private-methods" wants ^7.12.1 and could get 7.14.5, but got 7.13.0
Package "@babel/plugin-proposal-unicode-property-regex" wants ^7.4.4 and could get 7.14.5, but got 7.12.13
Package "@babel/plugin-transform-arrow-functions" wants ^7.12.1 and could get 7.14.5, but got 7.13.0
Package "@babel/plugin-transform-classes" wants ^7.12.1 and could get 7.14.5, but got 7.14.2
Package "@babel/plugin-transform-destructuring" wants ^7.12.1 and could get 7.14.7, but got 7.13.17
Package "@babel/plugin-transform-dotall-regex" wants ^7.4.4 and could get 7.14.5, but got 7.12.13
Package "@babel/plugin-transform-for-of" wants ^7.12.1 and could get 7.14.5, but got 7.13.0
Package "@babel/plugin-transform-parameters" wants ^7.12.1 and could get 7.14.5, but got 7.14.2
Package "@babel/plugin-transform-shorthand-properties" wants ^7.12.1 and could get 7.14.5, but got 7.12.13
Package "@babel/plugin-transform-spread" wants ^7.12.1 and could get 7.14.6, but got 7.13.0
Package "@babel/plugin-transform-template-literals" wants ^7.12.1 and could get 7.14.5, but got 7.13.0
Package "@babel/runtime-corejs2" wants ^7.12.5 and could get 7.13.9, but got 7.12.5
Package "@babel/runtime" wants ^7.0.0 and could get 7.14.6, but got 7.12.5
Package "@babel/runtime" wants ^7.1.2 and could get 7.14.6, but got 7.12.5
Package "@babel/runtime" wants ^7.10.2 and could get 7.14.6, but got 7.12.5
Package "@babel/runtime" wants ^7.11.2 and could get 7.14.6, but got 7.12.5
Package "@babel/runtime" wants ^7.12.1 and could get 7.14.6, but got 7.12.5
Package "@babel/runtime" wants ^7.12.5 and could get 7.14.6, but got 7.12.5
Package "@babel/runtime" wants ^7.2.0 and could get 7.14.6, but got 7.12.5
Package "@babel/runtime" wants ^7.3.1 and could get 7.14.6, but got 7.12.5
Package "@babel/runtime" wants ^7.4.0 and could get 7.14.6, but got 7.12.5
Package "@babel/runtime" wants ^7.5.0 and could get 7.14.6, but got 7.12.5
Package "@babel/runtime" wants ^7.5.5 and could get 7.14.6, but got 7.12.5
Package "@babel/runtime" wants ^7.6.3 and could get 7.14.6, but got 7.12.5
Package "@babel/runtime" wants ^7.7.2 and could get 7.14.6, but got 7.12.5
Package "@babel/runtime" wants ^7.7.6 and could get 7.14.6, but got 7.12.5
Package "@babel/runtime" wants ^7.8.4 and could get 7.14.6, but got 7.12.5
Package "@babel/runtime" wants ^7.13.0 and could get 7.14.6, but got 7.13.9
Package "@babel/template" wants ^7.12.13 and could get 7.14.5, but got 7.12.13
Package "@babel/template" wants ^7.12.7 and could get 7.14.5, but got 7.12.13
Package "@babel/template" wants ^7.3.3 and could get 7.14.5, but got 7.12.13
Package "@babel/traverse" wants ^7.1.0 and could get 7.14.7, but got 7.14.2
Package "@babel/traverse" wants ^7.12.9 and could get 7.14.7, but got 7.14.2
Package "@babel/traverse" wants ^7.13.0 and could get 7.14.7, but got 7.14.2
Package "@babel/traverse" wants ^7.14.0 and could get 7.14.7, but got 7.14.2
Package "@babel/traverse" wants ^7.14.2 and could get 7.14.7, but got 7.14.2
Package "@babel/traverse" wants ^7.4.5 and could get 7.14.7, but got 7.14.2
Package "@babel/types" wants ^7.0.0 and could get 7.14.5, but got 7.14.2
Package "@babel/types" wants ^7.12.1 and could get 7.14.5, but got 7.14.2
Package "@babel/types" wants ^7.12.13 and could get 7.14.5, but got 7.14.2
Package "@babel/types" wants ^7.12.7 and could get 7.14.5, but got 7.14.2
Package "@babel/types" wants ^7.13.12 and could get 7.14.5, but got 7.14.2
Package "@babel/types" wants ^7.14.0 and could get 7.14.5, but got 7.14.2
Package "@babel/types" wants ^7.14.2 and could get 7.14.5, but got 7.14.2
Package "@babel/types" wants ^7.3.0 and could get 7.14.5, but got 7.14.2
Package "@babel/types" wants ^7.3.3 and could get 7.14.5, but got 7.14.2
Package "@babel/types" wants ^7.4.4 and could get 7.14.5, but got 7.14.2
...
313 more lines...
```

Running again:
```
❯ yarn list --pattern @babel/preset-env
yarn list v1.22.10
└─ @babel/preset-env@7.14.7
✨  Done in 1.44s.
```

It works now. I can successfully build with only `@babel/preset-env` and have removed the other plugin from package.json and babel.config.js.

Really appreciate the help! Hopefully this info helps other people who search for the issue. Take care
